apiVersion: v1
kind: ServiceAccount
metadata:
  name: sfu-service-account
  namespace: sfu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sfu
  name: sfu-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sfu-role-binding
  namespace: sfu
subjects:
- kind: ServiceAccount
  name: sfu-service-account
  namespace: sfu
roleRef:
  kind: Role
  name: sfu-role
  apiGroup: rbac.authorization.k8s.io
